### ISSUE TITLE
mod shows as incompatible with spaced out DLC

### ISSUE THREAD

**Issue by marmot418** [isam2k/MiniBaseSO#1]
the list of active mods i have is in order of where they are in mods page

1. FreeResorceBuildings
2. Mod Updater
3. (vanilla + DLC) free skill points
4. bigger capacity
5. synthetic evolution

**Comment by isam2k** [comment]
I am unable to reproduce the issue. I have installed the same mods, made sure they are all up-to-date and played on the most recent stable version of the game and I can start a new game without any issues.

Can you give an exact description of what you're doing and maybe provide screenshots of the error message?

**Comment by marmot418** [comment]
I just looked after playing for a while and the game seems to have changed it's mind, it's now showing as compatible, don't know why

**Comment by marmot418** [comment]
found potential source, when I opened the game I got an insufficient space error message linked to my one drive and when I tracked down the folder it was the one for your mod (I shouldn't be getting this error since I am only using 8.9GB of the 1TB I have available on OneDrive
